### ISSUE TITLE
[Community Bug] Private key generation algorithm is WEAK

### ISSUE THREAD

**Issue by satyasys** [AElfProject/AElf#2152]
**Describe the bug**
Private key generation algorithm is not random enough.

**To Reproduce**
1. Go to https://wallet-test.aelf.io/
2. Click on Import Wallet
3. Change a letter in your existing private key
4. Go to https://apply-token-test.aelf.io/ and apply for free token
5. Come back and check your wallet

This proves private key generation algorithm is NOT random/strong enough.
Wallet: nhGHzRxUrygQbWBndb7iQp6wKQ98UiR7eHnitzompEYt8LC9s
Original privateKey and Modified privateKey
-------------------------b612b534b79cd73dbbe54392678786c251743a3c12c1a
-------------------------f612b534b79cd73dbbe54392678786c251743a3c12c1a

![Aelf Weak Private Key](https://user-images.githubusercontent.com/48247373/68179493-fe416800-ffdf-11e9-8dd3-ae00859e8d1b.PNG)

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS and version: [e.g. Ubuntu 18.04]
 - Dotnet core version [e.g. 2.2.106]

**Additional context**

**Comment by hzz780** [comment]
I am so sorry that we can not reproduce this.
Could you please provide a video or this two private key for us?

And we use https://www.npmjs.com/package/bip39 to generation private key.

**Comment by satyasys** [comment]
I imported wallet using modified private key not Mnemonics.
https://drive.google.com/open?id=1DxluiVfnvANC6E_dFZtPt4EXFT5AVKTY

**Comment by hzz780** [comment]
cool.
A good idea, we will hide the button instead of show the message.

**Comment by aelf-developer** [comment]
Dear satyasys,
Thank you for participating in aelf Enterprise 0.8.0 Beta version public testing.
We have received your issue and reviewed it. After the review, we decided to give you 128 ELF tokens as an award. Please contact aelf developer community staff for the award.

Contact Information:
QQ (Chinses): 1373175449 (Dayu)
WeChat (Chinses): a439714 (Dayu)
Telegram (English): @Samjia (Sam)

**Comment by satyasys** [comment]
Hello Aelf,

So you are paying 10 USD as bug bounty? Are giving alms or bounty? Kindly increase the amount.

**Comment by lpo1015** [comment]
it is so niggardly！

**Comment by aelf-developer** [comment]
Thank you very much for your suggestion! The suggested rewards based on your submission were suggested by our technical team.

We will host more developer events with great ELF token awards in aelf community, and please feel free to join it.

**Comment by aelf-developer** [comment]
After aelf technical team reevaluated this issue, this issue is not a bug on aelf wallet, it is a process optimization proposal. For specific reward rules, please refer to:
https://medium.com/aelfblockchain/aelf-launches-bug-bounty-c1e185f8aca4
aelf team highly values all suggestions you have made, every suggestion will be an important reference for our future development.

After an aelf team internal discussion, base on your active participation in this public test: an effective issue and an optimization proposal, you are indeed an active developer in aelf developer community. We will award you an additional 888 ELF tokens as a special contribution award. We hope that you will continue to participate in our development activities in the future and along with aelf technical team to build a vibrant community ecosystem.

**Comment by satyasys** [comment]
Thanks a lot AElf.

**Comment by hzz780** [comment]
repo: aelf-web-wallet
https://github.com/AElfProject/aelf-web-wallet/commit/9c00de2ba4f11221b719562b8cf9eb640378a620
