### ISSUE TITLE
[Pinned, DON'T take it down] IL code inspection, restriction and rewrite

### ISSUE THREAD

**Issue by gldeng** [AElfProject/AElf#727]
Byte code inspection/restriction/rewrite is required to ensure security, determinism and to support parallel processing

- [x] Disallow reference to Reflection, IO, Network and Threading types
- [x] Ensure byte code is verifiable (using [ILVerify](https://www.nuget.org/packages/Unofficial.CoreRT.ILVerify/))
- [x] No use of `float` and `double` to ensure determinism (Implemented but not enabled since there is arithmetic overflow with AEDPoS contract test cases.)
- [x] Disallow non-overflow checked arithmetic operations or rewrite non-overflow checked to overflow checked operations
- ~~[ ] Redesign state to have address based parallelizability (address can only be from contract or transaction parameters, and type casting and `new` of Address is not allowed)~~ (This is no longer required.)
- [x] Add ContractReference and restrict calls only via ContractReference (this is to help extraction metadata about call relationships)
- [x] Maybe inject usage (e.g. memory, method call, ...) meters in IL code
- ~~[ ] No method should be with 0 fee #783~~ (now we have mandatory resource fee)
...

**Comment by gldeng** [comment]
References:
[Stratis](https://github.com/stratisproject/StratisBitcoinFullNode/tree/master/src/Stratis.SmartContracts.CLR.Validation) is also using CLR and implemented similar controls.
[corda djvm](https://github.com/corda/corda/tree/master/djvm) is using JVM, but similar controls are required.

**Comment by aerkol** [comment]
> Disallow non-overflow checked arithmetic operations or rewrite non-overflow checked to overflow checked operations

Added a check to disallow unsafe opcodes in contracts but later realised that Google protobuf generated codes use many of them. It seems the right way is to replace the unsafe opcodes with the safe ones instead.

The challenge is to differentiate whether the operations were done with signed / unsigned variables to replace the unsafe opcode with a relevant safe one (ex: replace `add` with `add_ovf` or `add_ovf_un`) Inspected the IL codes of both signed and unsigned operations with an unsafe opcode and it seems it is difficult to identify the type of the variable that the result is assigned to.

Currently skipping this one to discuss later.

**Comment by loning** [comment]
can we make protobuf generated code use Span instead of using unsafe code?

**Comment by gldeng** [comment]
@rosona @aerkol @samfrb we pinned this issue. Please don't take it down.

**Comment by aerkol** [comment]
> can we make protobuf generated code use Span instead of using unsafe code?

I think the term "unsafe opcodes" I used is misleading (actually not related to the unsafe keyword in .net, just that the library we have SafeMath inspired me when calling those as unsafe opcodes).

I should use the term "non-ovf opcodes" or something like that instead. In current situation, if there is any overflow in the integers used in protobuf generated code then there won't be an exception because all of them use the non-ovf opcodes such as add, mul, sub, div. I am not sure how we can replace these with our safemath methods that use add_ovf, mul_ovf, sub_ovf, div_ovf etc.

**Comment by loning** [comment]
ok，let‘s ignore generated code in this case

发自我的 iPhone

**Comment by aerkol** [comment]
One potential solution to prevent unchecked (non-ovf) OpCodes in contracts:
https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/checked-compiler-option

If we enforce developers to build their contracts by using -checked flag or by enabling "Check for arithmetic overflow" that can be found in configuration of their project, then this issue will be solved, all generated code including protobuf generated codes will use checked (ovf) OpCodes.

Then we can disallow non-checked OpCodes in contract auditor and it will fail if the contract is built without this flag.

What do you guys think? Do you see any potential problems that may arise enforcing this -checked flag for builds?

**Comment by aerkol** [comment]
We enforce developers to compile their contracts with "check arithmetic overflow" checked so that in the event of an overflow, the contract will throw exception instead of running in a way that is not intended. If contracts contain any unchecked arithmetic opcode, deployment fails.

We enforce users compile their contracts with AElf contract patcher, that injects contract codes with a basic instruction meter to prevent malicious cases from exhausting node resources. (Such as infinite recursive calls, infinite loops etc.) It also helps us monitor whether there is any inefficiency with system contracts. The implementation is enough to reflect CPU consumption and the runtime complexity of the contracts.

We implemented static analysis in contract auditor to allow only specific libraries to prevent malicious usage in contracts and also to check whether the contract contains injected meter proxy.

We removed IL verifier due to several bugs noted in test case runs and also the nuget package seems to be no longer maintained and not compatible with netstandard 2.0 and above. We may consider readding it in the future.

Closing this issue.
